---
parameters:
    vmImage:
    # NOTE(rkm 2020-12-27) OS is required for the template conditions which are evaluated at compile-time before the Agent.OS is known
    os:

jobs:
    - job: dotnet_tests
      displayName: Dotnet Tests
      pool:
          vmImage: ${{ parameters.vmImage }}
      steps:
          - template: ../steps/vars.tmpl.yml
          - template: ../steps/use-dotnet.tmpl.yml
          - task: Cache@2
            displayName: Cache NuGet packages
            inputs:
                key: 'nuget | "$(Agent.OS)" | **/*.csproj | **/Directory.Build.props'
                path: $(NUGET_PACKAGES)
          - task: Cache@2
            displayName: Cache tesseract data
            inputs:
                key: 'tessdata | "$(Agent.OS)"'
                restoreKeys: |
                    tessdata
                path: $(TESS_CACHE_DIR)
                cacheHitVar: TESS_CACHE_RESTORED
          - task: Bash@3
            displayName: Download tessdata if cache not restored
            condition: eq(variables.TESS_CACHE_RESTORED, 'false')
            inputs:
                targetType: "inline"
                script: |
                    set -euxo pipefail
                    mkdir -p "$(TESS_CACHE_DIR)"
                    curl -L \
                        https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata \
                        > "$(TESS_CACHE_DIR)/eng.traineddata"
                    ls -l "$(TESS_CACHE_DIR)"
          - task: Bash@3
            displayName: Symlink tessdata into the repo
            inputs:
                targetType: "inline"
                script: |
                  ln -s \
                    "$(TESS_CACHE_DIR)/eng.traineddata" \
                    "$(Build.SourcesDirectory)/data/tessdata/eng.traineddata"
          - ${{ if eq( parameters.os, 'linux' ) }}:
                - template: ../steps/docker-cache.tmpl.yml
                  parameters:
                      os: ${{ parameters.os }}
                      language: dotnet
                - template: ../steps/linux-dotnet-docker.yml
          - ${{ if eq( parameters.os, 'win' ) }}:
                - template: ../steps/win-dotnet-services.yml
          - template: ../steps/rdmp-setup.tmpl.yml
            parameters:
                os: ${{ parameters.os }}
          - task: Bash@3
            displayName: Run Dotnet tests
            inputs:
                targetType: inline
                script: python .azure-pipelines/scripts/run-dotnet-tests.py
                failOnStderr: true
          - task: Bash@3
            displayName: Upload coverage
            inputs:
              targetType: inline
              script: |
                set -euxo pipefail
                dotnet tool update --global coveralls.net
                csmacnz.Coveralls \
                  --opencover \
                  -i coverage/coverage.opencover.xml \
                  --repoToken "foo" \
                  --commitId "$(Build.SourceVersion)" \
                  --commitBranch "$(Build.SourceBranchName)" \
                  --commitAuthor "$(git show -s --format='%an')" \
                  --commitEmail "$(git show -s --format='%ae')" \
                  --commitMessage "$(Build.SourceVersionMessage)" \
                  --jobId "$(Build.BuildId)" \
                  --dryrun

    - job: java_tests
      displayName: Java Tests
      pool:
          vmImage: ${{ parameters.vmImage }}
      steps:
          - template: ../steps/vars.tmpl.yml
          - task: JavaToolInstaller@0
            displayName: Use Java 11
            inputs:
                versionSpec: "11"
                jdkArchitectureOption: "x64"
                jdkSourceOption: "PreInstalled"
          - task: Cache@2
            displayName: Cache Maven local repo
            inputs:
                key: 'maven | "$(Agent.OS)" | **/pom.xml'
                restoreKeys: |
                    maven | "$(Agent.OS)"
                    maven
                path: $(MAVEN_CACHE_FOLDER)
          - ${{ if eq( parameters.os, 'linux' ) }}:
                - template: ../steps/docker-cache.tmpl.yml
                  parameters:
                      os: ${{ parameters.os }}
                      language: java
                - template: ../steps/linux-java-docker.yml
          - ${{ if eq( parameters.os, 'win' ) }}:
                - task: Bash@3
                  displayName: Skip Java integration tests on Windows
                  inputs:
                      targetType: "inline"
                      script: echo "##vso[task.setvariable variable=MVN_PROFILE]-PunitTests"
          - task: Bash@3
            displayName: Run Java tests
            inputs:
                filePath: .azure-pipelines/scripts/run-java-tests.bash
                # TODO(rkm 2020-12-11) See if we can silence the current bogus stderr output (log4j warning & SMI_LOGS_ROOT)
                failOnStderr: false
                arguments: $(MVN_PROFILE)

    - job: python_tests
      displayName: Python Tests
      pool:
          vmImage: ${{ parameters.vmImage }}
      steps:
          - template: ../steps/vars.tmpl.yml
          - template: ../steps/create-venv.tmpl.yml
            parameters:
              os: ${{ parameters.os }}
          - task: Bash@3
            displayName: Install requirements
            inputs:
                targetType: "inline"
                script: |
                    set -euxo pipefail
                    "$(python_exe)" -m pip \
                    install \
                        -r src/common/Smi_Common_Python/requirements.txt \
                        -r src/common/Smi_Common_Python/requirements-dev.txt
          - task: Bash@3
            displayName: Run Python Tests
            inputs:
                targetType: "inline"
                script: |
                    set -exuo pipefail
                    "$(python_exe)" -m pytest \
                    src/common/Smi_Common_Python/SmiServices/*.py
